---
title: "Datenauswertung"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(jmv)
library(ggplot2)

df <- readRDS("data.rds")

```

# Korrelationen

```{r Korrelationen}

# Hypothese 1: Arbeitszufriedenheit, Switch-off

#### Hypothesen "richtig reinschreiben"

## Anpassung JRH: Das sind einzelne Items. Methodisch ist das okay, solange wir Spearman oder Kendall verwenden. Die Funktion cor() braucht aber zwei numerics. 

cor(as.numeric(df$ZUFR_GR), as.numeric(df$SOFF_GR), method = "spearman")
cor(as.numeric(df$ZUFR_GR), as.numeric(df$SOFF_GR), method = "kendall")

cor.test(as.numeric(df$ZUFR_GR), as.numeric(df$SOFF_GR), method = "spearman")
cor.test(as.numeric(df$ZUFR_GR), as.numeric(df$SOFF_GR), method = "kendall")



```
signifikant, kendall tau, 0.186. es gibt zusammenhang aber nur sehr schwach. deshalb keine aussagekraft. beim ausformulieren darauf achten wie die hypothesen formuliert waren.
```{r Visualisierung Hypothese 1}


df %>% ggplot() + aes(x = ZUFR, y = SOFF) + geom_point(alpha = 0.5) + geom_smooth(method = lm, color = "black") + cowplot::theme_half_open() + labs(x = "Zufriedenheit", y = "Switch-off", title = "Zufriedenheit und Switch-off korrelieren negativ.")



df %>% ggplot() + aes(x = ZUFR_GR, y = SOFF_GR) +
geom_jitter(alpha = 0.25, width = 0.2, height = 0.2) + geom_smooth(method = lm, color = "black") + cowplot::theme_half_open() + labs(x = "Zufriedenheit", y = "Switch-off", title = "robo_bed und robo_med korrelieren positiv.")

```








```{r}
# Hypothese 2: Position der Arbeit, Switch-off

cor.test(as.numeric(df$JOB_GR), as.numeric(df$SOFF_GR), method = "spearman")
cor.test(as.numeric(df$JOB_GR), as.numeric(df$SOFF_GR), method = "kendall")





```

wenn berichten dann werte ausgeben lassen.

```{r}
# Hypothese 3: Remote Working, Switch-off

cor.test(as.numeric(df$MA_GR), as.numeric(df$SOFF_GR), method = "pearson")
cor.test(as.numeric(df$MA_GR), as.numeric(df$SOFF_GR), method = "spearman")
cor.test(as.numeric(df$MA_GR), as.numeric(df$SOFF_GR), method = "kendall")

  
  
  
  
```

wahrscheinlich nehmen wir die ganze zeit Kendall. pearson wahrscheinlich überhaupt nicht



```{r}
# Hypothese 4: Flexibilität, Arbeitszufriedenheit


cor.test(as.numeric(df$FLEX_GR), as.numeric(df$ZUFR_GR), method = "spearman")
cor.test(as.numeric(df$FLEX_GR), as.numeric(df$ZUFR_GR), method = "kendall")


```

```{r}

# Hypthese 5: Entfernung zur Arbeit, Switch-off

cor.test(as.numeric(df$EN_GR), as.numeric(df$SOFF_GR), method = "spearman")
cor.test(as.numeric(df$EN_GR), as.numeric(df$SOFF_GR), method = "kendall")


```




# Unterschiede


```{r}

# Hypothese 1: Arbetszeit-Zufriedenheit, Switch-Off


#t.test(as.numeric(df$SOFF_GR), mu=3.5)
#df_AZZ_GR_unzufrieden <- filter(df, AZZ_GR == "unzufrieden")
#df_AZZ_GR_sehrzufrieden <- filter(df, AZZ_GR == "sehr zufrieden")


#JRH: Das hier geht:
#t.test(as.numeric(df_AZZ_GR_unzufrieden$SOFF_GR), as.numeric(df_AZZ_GR_sehrzufrieden$SOFF_GR))


#df_AZZ_GR_unzufrieden$SOFF_GR <- as.numeric(df_AZZ_GR_unzufrieden$SOFF_GR)
#df_AZZ_GR_sehrzufrieden$SOFF_GR <- as.numeric(df_AZZ_GR_sehrzufrieden$SOFF_GR)

#wilcox.test(df_AZZ_GR_unzufrieden$SOFF_GR, df_AZZ_GR_sehrzufrieden$SOFF_GR)



t.test(df_AZZ_GR_unzufrieden$SOFF, df_AZZ_GR_sehrzufrieden$SOFF)



```





```{r}
# Hypothese 2: geringe Arbeitszeit (bis 29 Std./Woche), Arbeitsintensität, SWitch off


df %>% ANOVA(dep = "SOFF", factors = c("AZ_GR", "AI_GR"))



#df$SOFF_GR <- as.numeric(df$SOFF_GR)

#df %>% 
  #ANOVA(dep = "SOFF_GR", factors = c("AZ_GR", "AI_GR"))






```







```{r}

# Hypothese 3: Anstellungsdauer, Switch-off







```



```{r}

# Hypothese 4: mobiles Arbeiten, Switch-Off





```

